title = "The Things Stack for LoRaWAN"

baseURL = "http://localhost/"

theme = "the-things-stack"

disableKinds = [
  "taxonomy",
  "taxonomyTerm",
  "RSS",
]

enableGitInfo = true

languageCode = "en-us"
languageName = "English"

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "The Things Stack for LoRaWAN"
  keywords = []
  github_repository = "https://github.com/TheThingsIndustries/lorawan-stack-docs"
  github_repository_edit = "https://github.com/TheThingsIndustries/lorawan-stack-docs/blob/master/doc/content"
  tts_github_repository = "https://github.com/TheThingsNetwork/lorawan-stack"
  version = "3.27.2"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.contributing]]
    name = "GitHub"
    url = "https://github.com/TheThingsIndustries/lorawan-stack-docs"
    weight = 1

  [[menu.about_us]]
    name = "The Things Industries"
    url = "https://www.thethingsindustries.com"
    weight = 2

  [[menu.buttons]]
    name = "Get The Things Stack"
    url = "https://accounts.thethingsindustries.com/fee-calculator"
    weight = 1
