googleAnalytics = ""

[params]
  [params.search]
    enabled = false
    apikey = ""
    index = ""
    appid = ""
  [params.intercom]
    enabled = false
    appid = ""
  [params.feedback]
    enabled = false
    campaign = ""
